apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - containerPort: 80
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "my-secret-pw"
      - name: MYSQL_DATABASE
        value: "mysql-db-1"
